name: ml-env
channels:
  - conda-forge
dependencies:
  - python==3.12
  - pathlib
  - toml
  - resolve-robotics-uri-py
  - numpy
  - scipy
  - matplotlib
  - idyntree
  - tabulate
  - optuna
  - rich
  - pandas
  - openpyxl
  - wandb
  - huggingface_hub
  - scikit-learn
  - nvidia/label/cuda-12.8.0::cuda
  - libtorch==2.7.1
  - pytorch-gpu==2.7.1
  - pytorch=2.7.1
  - pytorch-model-summary
  - pytorch_geometric
  - onnx
  - onnxruntime
  - plotly
  - pytorch-msssim
  - pip
  - pip:
    - open3d
    - torchsummary
variables:
  CUBLAS_WORKSPACE_CONFIG: :4096:8
#
# After installing remember to run:
# conda install intel-openmp --force-reinstall
