name: ml-env
channels:
  - conda-forge
dependencies:
  - python
  - pathlib
  - toml
  - resolve-robotics-uri-py
  - numpy
  - scipy
  - matplotlib
  - idyntree
  - tabulate
  - optuna
  - rich
  - pandas
  - scikit-learn
  - nvidia/label/cuda-12.8.0::cuda
  - libtorch==2.7.1
  - pytorch-gpu==2.7.1
  - pytorch=2.7.1
  - pytorch-model-summary
  - wandb
  - huggingface_hub
  - open3d
  - pytorch_geometric
variables:
  CUBLAS_WORKSPACE_CONFIG: :4096:8
