name: ml-env
channels:
  - conda-forge
  - robotology
dependencies:
  - python==3.11.0
  - pathlib
  - toml
  - numpy==1.26.4
  - scipy
  - idyntree
  - resolve-robotics-uri-py
  - matplotlib
  - nvidia/label/cuda-12.4.0::cuda
  - nomkl
  - tabulate
  - openpyxl
  - huggingface_hub
  - optuna
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - torch
    - torchvision
    - torchaudio
    - torchsummary
    - torchinfo
    - open3d
    - wandb
    - plotly
