---
name: task-template
about: Template for structured task issue.
title: ''
labels: ''
assignees: ''

---

name: 📝 Task
description: Use this template to create a new task.
title: "[TASK] "
labels: ["task"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: 📄 Brief Description
      description: Describe the task in more detail. Include context or background info.
      placeholder: "Why is this task needed? Any relevant information or links."
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: ✅ Definition of Done
      description: What needs to be true for this task to be considered complete?
      placeholder: |
        E.g.
        - Functionality is implemented
        - Code is peer-reviewed
        - Tests are written and passing
    validations:
      required: true
